

package Problems;

public class Problem2 {
/*
    Problem 2: Even Fibonacci numbers
    
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     
    */
    private final int Max = 4000000;
    
    public Problem2(){
        int f=1, s=1, n=0, sum=0;
        while (n<=Max){
            n = f+s;
            if(n%2==0){
                sum += n;
            }
            f = s;
            s = n;
        }
        System.out.println("Problem 2 result: " + sum);
    }
}
